[package]
name = "markdown"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
pulldown-cmark = { version = "0.5.3", default-features = false }
wasm-bindgen = "=0.2.55"
